# Site settings
title: "Roads Untraveled"
email: super-ops@ssiops.org
description: "♪ Weep not for roads untraveled ♪\n♪ Weep not for sights unseen ♪\n♪ May your love never end ♪\n♪ And if you need a friend ♪\n♪ There's a seat here alongside me ♪"
baseurl: "/roads-untraveled" # the subpath of your site
url: "http://akasfei.github.io" # the base hostname & protocol for your site
twitter_username: akasfei
github_username:  akasfei
contact: SierraSix

# Build settings
markdown: kramdown
highlighter: rogue
